filetype on "Enable filetype detection
filetype indent on "Enable automatic indentation

set nu rnu "Set hybrid linenumbers
syntax on "Syntax highlighting
set hlsearch "Highlight search maches
set incsearch "Autojump to match
set smartcase "Lower case matches upper, Upper doesn't match lower

set showmode "Show the mode at the bottom
set showcmd "Show the command Im typing

set encoding=utf-8 "UTF-8 Default (As it just should be)

hi CursorLine cterm=NONE ctermbg=3
set nocursorline "cursorline (Temporarily disabled)

set autoindent "Auto indentation
set smartindent "Language aware indentation
set tabstop=4 "Tabs should appear 4 characters long
set softtabstop=0 noexpandtab "Tabs (not spaces, but I have them properly aligned)
set shiftwidth=4 "One level of indentation should be 4 characters long (one tab, remember?)

set wrap "Wrap lines
set wrapmargin=5 "Looks nicer
set laststatus=2 "Always show statusbar
set ruler "Position at bottom right

set showmatch "Other parenthesis (or whatever other couple) will be highlighted

set spelllang=en_us "Spell checking (Is enabled by mapping below)
map ,s :set spell!

set noerrorbells "It just sucks
set visualbell "But some indication is needed

set scrolloff=5 "Scroll offset of 5

set autoread "Be sensible to outside changes

set wildmenu "Command completion choice
set wildmode=longest:list,full "Menu display style

set list "Show whitespace characters
set listchars=tab:--] "Just show tabs with '---]'
