set nu rnu "Set hybrid linenumbers
set autoindent "Auto indentation
syntax on "Syntax highlighting
set hlsearch "Highlight search maches

hi CursorLine cterm=NONE ctermbg=3
set cursorline "cursorline

set smarttab
set softtabstop=2 "tab customisation
